// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyWOtpQ1WQOs81cz-OZhQ2CQsfywg1F50',
    appId: '1:668503627967:web:bb62fb0bae7501170bce0a',
    messagingSenderId: '668503627967',
    projectId: 'reimburse-rb',
    authDomain: 'reimburse-rb.firebaseapp.com',
    storageBucket: 'reimburse-rb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLp3FHU3ILBe5FYSwsBpUrR9yaQzwafdI',
    appId: '1:668503627967:android:7b7ea3845f4e138c0bce0a',
    messagingSenderId: '668503627967',
    projectId: 'reimburse-rb',
    storageBucket: 'reimburse-rb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP0KX-nagtoUDTHfY_cjOER_8EkGBqr_A',
    appId: '1:668503627967:ios:d4855d9ff40773670bce0a',
    messagingSenderId: '668503627967',
    projectId: 'reimburse-rb',
    storageBucket: 'reimburse-rb.appspot.com',
    iosBundleId: 'com.example.reimburseRb',
  );
}
